import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import HomeMonitor from "../components/HomeMonitor/homeMonitor.js";

export default function Home() {
   return (
      <div className={styles.container}>
         <Head>
            <title>GamesLogger</title>
            <meta name="description" content="Generated by create next app" />
         </Head>
         <HomeMonitor />
      </div>
   );
}
